export const API_POKEMON= 'https://pokeapi.co/api/v2/pokemon';
export const SEND_REQUEST='SEND_REQUEST';
export const REQUEST_SUCCESS= 'REQUEST_SUCCESS';
export const REQUEST_FAILURE= 'REQUEST_FAILURE';
export const REQUEST_LOADING= 'REQUEST_LOADING';
export const GET_STUDENTS = 'GET_STUDENTS';
export const RUTAQUEGABIAUNNOMEPASA = 'RUTAQUEGABIAUNNOMEPASA';
export const GET_STUDENTS_SUCESS = 'GET_STUDENTS_SUCESS';
export const GET_STUDENTS_FAILURE = 'GET_STUDENTS_FAILURE';
export const GET_STUDENTS_AZ = 'GET_STUDENTS_AZ';
export const GET_STUDENTS_ZA = 'GET_STUDENTS_ZA';
export const GET_STUDENTS_HIGH_SCORE = 'GET_STUDENTS_HIGH_SCORE';
export const GET_PUBLIC_FOLLOWS = 'GET_PUBLIC_FOLLOWS';
export const GET_PUBLIC_FOLLOWS_SUCESS = 'GET_PUBLIC_FOLLOWS_SUCESS';
export const SET_REGISTER_TRUE = 'SET_REGISTER_TRUE'; // despues hay que borrarla 
export const GET_INFO_USER_SUCCES = 'GET_INFO_USER_SUCCES';
export const SET_REGISTER_TRUE_SUCCES = 'SET_REGISTER_TRUE_SUCCES';

export const GET_PUBLICATIONS_BUSINESS = 'GET_PUBLICATIONS_BUSINESS'; 
export const GET_PUBLICATIONS_BUSINESS_SUCCESS = 'GET_PUBLICATIONS_BUSINESS_SUCCESS';
export const URL_PEDIDO = "urlpedidoxd" // reemplazar por la ruta de pedidos de publicaciones de empresas
export const GET_PUBLICATIONS_TECHNOLOGIES = "GET_PUBLICATIONS_TECHNOLOGIES";
export const GET_PUBLICATIONS_DEVTYPE = "GET_PUBLICATIONS_DEVTYPE";
export const GET_PUBLICATIONS_ENGLISH = "GET_PUBLICATIONS_ENGLISH";
export const GET_PUBLICATIONS_WORK_MODALITY = "GET_PUBLICATIONS_WORK_MODALITY";
export const GET_PUBLICATIONS_UBICATION = "GET_PUBLICATIONS_UBICATION";

export const GET_PUBLICATION_STUDENTS = "GET_PUBLICATION_STUDENTS";
export const GET_PUBLICATION_STUDENTS_SUCCESS = "GET_PUBLICATION_STUDENTS_SUCCESS";
export const GET_PUBLICAT_TECHNOLOGIES = "GET_PUBLICAT_TECHNOLOGIES";
export const GET_PUBLICAT_ENGLISH = "GET_PUBLICAT_ENGLISH";
export const GET_PUBLICAT_WORKMODALITY = "GET_PUBLICAT_WORKMODALITY";
export const GET_PUBLICAT_UBICATION = "GET_PUBLICAT_UBICATION";
export const GET_PUBLICAT_DEVTYPE = "GET_PUBLICAT_DEVTYPE";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";

export const URL_PEDIDO_USER = "URL_PEDIDO_USER"; // URL QUE TRAE INFO DE USUARIO
export const GET_INFO_USER = "GET_INFO_USER";
export const GET_INFO_USER_SUCCESS = "GET_INFO_USER_SUCCESS";



export const POST_USER= 'POST_USER';
export const POST_USER_SUCCESS='POST_USER_SUCCESS';
export const URL_POST='';
export const HENRY_LOGO ='https://blog.soyhenry.com/content/images/2021/03/151211491_440151970756357_8005198803636550092_o.jpg';